const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');

const indexHtml = fs.readFileSync('index.html', 'utf8');
const compatHtml = fs.readFileSync('reader.html', 'utf8');
const css = fs.readFileSync('assets/reader.css', 'utf8');
const app = fs.readFileSync('assets/reader.js', 'utf8');
const en = fs.readFileSync('assets/i18n/en-US.js', 'utf8');
const zh = fs.readFileSync('assets/i18n/zh-CN.js', 'utf8');
const zhTw = fs.readFileSync('assets/i18n/zh-TW.js', 'utf8');
const i18nIndex = fs.readFileSync('assets/i18n/index.js', 'utf8');

assert.match(indexHtml, /<link rel="stylesheet" href="assets\/reader\.css(?:\?[^"]+)?">/, 'reader should load external CSS');
assert.match(indexHtml, /localStorage\.getItem\("chatgpt-export-reader\.settings\.v1"\)/, 'reader should apply saved theme before CSS loads');
assert.match(indexHtml, /document\.documentElement\.dataset\.theme/, 'reader should set initial theme on the root element');
assert.match(indexHtml, /<link rel="icon" href="openai\.svg" type="image\/svg\+xml">/, 'reader should use the OpenAI icon as its favicon');
assert.match(indexHtml, /<span class="brand-mark" aria-hidden="true"><\/span>/, 'reader should show a CSS-colored OpenAI icon in the sidebar brand');
assert.match(indexHtml, /vendor\/jszip\.min\.js/, 'reader should load local JSZip');
assert.doesNotMatch(indexHtml, /vendor\/pdf-lib\.min\.js/, 'reader should not load pdf-lib for browser print export');
assert.doesNotMatch(indexHtml, /vendor\/fontkit\.umd\.min\.js/, 'reader should not load fontkit for browser print export');
assert.doesNotMatch(indexHtml, /assets\/fonts\/pdf-fonts\.js/, 'reader should not load embedded PDF font fallback data');
assert.match(indexHtml, /assets\/i18n\/en-US\.js(?:\?[^"]+)?/, 'reader should load English locale');
assert.match(indexHtml, /assets\/i18n\/zh-CN\.js(?:\?[^"]+)?/, 'reader should load Simplified Chinese locale');
assert.match(indexHtml, /assets\/i18n\/zh-TW\.js(?:\?[^"]+)?/, 'reader should load Traditional Chinese locale');
assert.match(indexHtml, /assets\/reader\.js(?:\?[^"]+)?/, 'reader should load external app JS');
assert.match(compatHtml, /location\.replace\('index\.html'/, 'legacy reader.html should redirect to index.html');

assert.ok(fs.existsSync('vendor/jszip.min.js'), 'JSZip vendor file should exist');
assert.match(fs.readFileSync('vendor/jszip.min.js', 'utf8'), /JSZip v3\.10\.1/, 'reader should vendor JSZip 3.10.1');

assert.match(indexHtml, /打开你的 ChatGPT 导出包/, 'reader should expose the ZIP drop empty state');
assert.match(indexHtml, /id="settingsModal"/, 'reader should include settings modal');
assert.match(indexHtml, /id="languageSelect"/, 'settings should include language select');
assert.match(indexHtml, /id="themeSelect"/, 'settings should include theme select');
assert.match(indexHtml, /id="defaultImportModeSelect"/, 'settings should include import mode select');
assert.match(indexHtml, /id="storageUsedValue"/, 'settings should show used browser storage');
assert.match(indexHtml, /id="storageRemainingValue"/, 'settings should show remaining browser storage');
assert.match(indexHtml, /id="settingsClearButton"/, 'settings should contain the clear import danger action');
assert.match(indexHtml, /id="appDialogModal"/, 'reader should include a reusable app-styled dialog modal');
assert.doesNotMatch(indexHtml, /rememberImportChoiceSetting/, 'settings should not expose the import dialog remember checkbox');
assert.match(indexHtml, /id="exportPdfButton"/, 'reader should expose PDF export action');
assert.match(indexHtml, /id="mobilePdfButton"/, 'mobile topbar should expose PDF export action');
assert.doesNotMatch(indexHtml, /mobileChooseButton/, 'mobile topbar should not keep the old ZIP plus button');
assert.match(indexHtml, /id="mediaLibraryButton"/, 'sidebar should include library');
assert.doesNotMatch(indexHtml, /id="filesButton"/, 'sidebar should not include a files entry');
assert.match(indexHtml, /id="assetLibrary"/, 'reader should include an asset library page');
assert.match(indexHtml, /id="assetLibraryHeaderActions"/, 'asset library should expose sticky header actions');
assert.match(indexHtml, /id="railMediaLibraryButton"[^>]+title="资料库"/, 'collapsed rail should label the library as library');
assert.doesNotMatch(indexHtml, /id="railFilesButton"/, 'collapsed rail should not include files');
assert.doesNotMatch(indexHtml, /id="clearButton"/, 'clear import should not remain in the sidebar');
assert.doesNotMatch(indexHtml, /id="railClearButton"/, 'clear import should not remain in the collapsed rail');
assert.match(indexHtml, /rememberImportChoiceInput/, 'import choice should support remembering a choice');
assert.match(indexHtml, /id="confirmImportChoiceButton"/, 'import choice should submit from a dialog action button');
assert.match(indexHtml, /dialog-actions/, 'dialogs should use a footer action area');
assert.match(css, /:root\[data-theme="dark"\]/, 'reader should support dark theme variables');
assert.match(css, /settings-modal/, 'reader should style settings modal');
assert.match(css, /\.brand-mark\s*\{[\s\S]*width: 24px;[\s\S]*height: 24px;[\s\S]*mask: url\("\.\.\/openai\.svg"\)/, 'sidebar brand icon should use the OpenAI icon mask');
assert.match(css, /:root\[data-theme="dark"\] \.brand-mark\s*\{[\s\S]*background: #fff/, 'dark mode brand icon should render white');
assert.match(css, /\.thread-header\s*\{[\s\S]*border-bottom: 1px solid var\(--border-soft\)/, 'thread header should have a divider');
assert.match(css, /\.thread-pdf-button\s*\{[\s\S]*width: 36px;[\s\S]*height: 36px/, 'desktop PDF export should be a compact icon button');
assert.match(css, /\.reader\.visible \.thread-pdf-button\s*\{[\s\S]*position: absolute;[\s\S]*right: 24px/, 'desktop PDF export should sit at the viewport top right');
assert.match(css, /\.mobile-pdf-button\s*\{[\s\S]*width: 36px;[\s\S]*height: 36px/, 'mobile PDF export should be a compact icon button');
assert.match(css, /@media \(max-width: 840px\)[\s\S]*\.thread-header\s*\{[\s\S]*display: none;/, 'mobile should hide the second thread header');
assert.match(css, /@media \(max-width: 840px\)[\s\S]*\.reader\.visible \.thread-pdf-button\s*\{[\s\S]*display: none;/, 'mobile should hide the desktop PDF export button');
assert.match(css, /\.checkbox-field\s*\{[\s\S]*display: flex !important;[\s\S]*flex-direction: row !important/, 'PDF checkbox labels should stay on the same row');
assert.match(css, /\.danger-button/, 'clear import should be styled as a danger action');
assert.match(css, /\.asset-library/, 'reader should style the asset library page');
assert.match(css, /\.library-table/, 'asset library should support list view');
assert.match(css, /\.library-grid/, 'asset library should support grid view');
assert.match(css, /\.library-bulk-actions/, 'asset library should style selected-item bulk actions');
assert.match(css, /\.library-select-toggle/, 'asset library should style card selection toggles');
assert.doesNotMatch(css, /\.library-new-button/, 'asset library should not style the removed new menu button');
assert.match(css, /\.dialog-button\.primary/, 'dialogs should use primary pill action buttons');
assert.match(css, /\.dialog-button\.secondary/, 'dialogs should use secondary pill action buttons');

assert.match(app, /const DEFAULT_SETTINGS = \{[\s\S]*language: "auto"[\s\S]*theme: "system"[\s\S]*defaultImportMode: "append"/, 'default settings should be auto language, system theme, append import');
assert.match(app, /function shareIconSvg/, 'reader should provide a share-style icon for mobile PDF export');
assert.match(app, /function importIconSvg\(\) \{[\s\S]*M7 4\.75h7\.2L17 7\.55/, 'import ZIP should use a file-import icon');
assert.match(app, /dom\.mobilePdfButton\.innerHTML = shareIconSvg\(\)/, 'mobile PDF export should render as an icon');
assert.match(app, /dom\.exportPdfButton\.innerHTML = shareIconSvg\(\)/, 'desktop PDF export should render as the same share icon');
assert.match(app, /dom\.mobilePdfButton\.addEventListener\("click", openPdfExportModal\)/, 'mobile PDF export should open the PDF dialog');
assert.doesNotMatch(app, /mobileChooseButton/, 'mobile ZIP plus button wiring should be removed');
assert.match(app, /const DB_NAME = "chatgpt-export-reader"/, 'reader should use IndexedDB cache');
assert.match(app, /db\.createObjectStore\("conversations", \{ keyPath: "id" \}\)/, 'IndexedDB should store conversations by id');
assert.match(app, /db\.createObjectStore\("assets", \{ keyPath: "path" \}\)/, 'IndexedDB should store assets by path');
assert.match(app, /restoreLibraryFromStorage/, 'reader should restore cached library on load');
assert.match(app, /saveLibraryToStorage/, 'reader should save imports to cache');
assert.match(app, /clearStoredLibrary/, 'clear should delete cached library');
assert.match(app, /navigator\.storage\?\.estimate/, 'settings should estimate browser storage usage');
assert.match(app, /formatBytes/, 'settings should format storage sizes');
assert.match(app, /openAssetLibrary/, 'sidebar library entries should open asset library views');
assert.match(app, /openAssetLibrary\("all"\)/, 'library sidebar entry should open the full asset library');
assert.match(app, /M14\.402 2\.648a2\.2 2\.2 0 0 1 2\.547 1\.783/, 'library should use the matching ChatGPT library icon path');
assert.match(css, /svg\.library-icon,[\s\S]*stroke: none/, 'library icon should not inherit sidebar SVG stroke weight');
assert.match(app, /libraryRecords/, 'asset library should filter cached images and files');
assert.match(app, /librarySelected: new Set/, 'asset library should track selected assets');
assert.doesNotMatch(app, /libraryFolders/, 'asset library should not persist asset categories');
assert.match(app, /libraryNames/, 'asset library should persist display names');
assert.match(app, /renderLibrarySelectionActions/, 'asset library should render a selected-item toolbar');
assert.match(app, /library-card-overlay[\s\S]*library-card-name[\s\S]*library-card-size/, 'grid library cards should show name and size inside the preview overlay');
assert.match(css, /\.library-card:hover \.library-card-overlay,[\s\S]*opacity: 1/, 'grid library card metadata should appear on hover');
assert.match(css, /padding: 12px 48px 12px 12px/, 'grid library metadata should leave room for the selection control');
assert.doesNotMatch(css, /\.library-controls\s*\{[\s\S]*position: sticky/, 'library controls should scroll as part of the sticky library header');
assert.match(app, /downloadLibraryRecords/, 'asset library should download one or many selected assets');
assert.match(app, /deleteLibraryRecords/, 'asset library should remove selected assets from cached library');
assert.doesNotMatch(app, /moveLibraryRecords/, 'asset library should not move assets into saved categories');
assert.match(app, /renameLibraryRecord/, 'asset library should rename asset display names');
assert.match(app, /openAppDialog/, 'library rename should use the reusable app dialog');
assert.match(app, /confirmAppDialog/, 'destructive actions should use the reusable app dialog');
assert.match(app, /assetRecordDisplayName/, 'chat attachments should use renamed library display names without changing source records');
assert.doesNotMatch(app, /data-library-new-toggle/, 'asset library should not include a new-item menu');
assert.match(app, /data-sort-toggle/, 'asset library should include sorting controls');
assert.match(indexHtml, /id="pdfExportModal"/, 'PDF export should use a configurable export dialog');
assert.match(app, /function buildPdfExportDocument/, 'PDF export should build a dedicated export document');
assert.match(app, /function pdfExportDocumentStyles/, 'PDF export should inline isolated PDF document styles');
assert.match(app, /window\.open\("", "_blank"\)/, 'PDF export should render in an isolated browser window');
assert.match(app, /window\.print\(\)/, 'PDF export should use browser print layout');
assert.match(app, /renderPdfExportSources/, 'PDF export should include rendered message sources');
assert.doesNotMatch(app, /PDFDocument\.create/, 'PDF export should not hand-draw PDFs with pdf-lib');
assert.doesNotMatch(i18nIndex, /pdfFont/, 'locale metadata should not carry obsolete PDF font paths');

assert.match(app, /dedupeConversations/, 'reader should dedupe conversations during imports');
assert.match(app, /conversationMergeKeys/, 'reader should merge conversations with multiple dedupe keys');
assert.match(app, /conversationBranchId/, 'reader should preserve exported conversation branches during dedupe');
assert.match(app, /function countConversationTurns/, 'reader should count visible conversations by user turns');
assert.match(app, /t\("turn\.count", \{ count: countConversationTurns\(conversation\.messages\) \}\)/, 'conversation list should show localized user-turn counts');
assert.doesNotMatch(app, /\$\{conversation\.messages\.length\} 条/, 'conversation list should not show raw message counts');
assert.match(app, /conversationSortOrder/, 'reader should track conversation sort order');
assert.match(app, /conversation-sort-button/, 'conversation list should render a sort toggle next to the first group title');
assert.match(app, /conversation\.sortNewest/, 'reader should expose conversation sort labels');
assert.match(css, /\.conversation-sort-button/, 'reader should style the conversation sort toggle');
assert.match(app, /id:\$\{conversation\.conversationId\}:\$\{conversation\.branchId\}/, 'reader should dedupe JSON conversations by branch id');
assert.doesNotMatch(app, /appendModeInput/, 'append import should not be a persistent sidebar toggle');
assert.doesNotMatch(app, /window\.confirm/, 'reader should not use browser-native confirm dialogs');
assert.doesNotMatch(app, /window\.prompt/, 'reader should not use browser-native prompt dialogs');
assert.match(app, /mergeConversations/, 'reader should merge conversations during append imports');
assert.match(app, /setPendingImportMode/, 'import choice should select a mode before submitting');
assert.match(app, /table-copy/, 'reader should expose copy controls for markdown tables');
assert.match(app, /table-col-label/, 'reader should reserve a stable label column for tables');
assert.match(app, /tableAlignments = line/, 'reader should parse markdown table alignment markers');
assert.match(app, /class="align-\$\{align\}"/, 'reader should apply table alignment classes');
assert.match(app, /markdown-divider/, 'reader should render markdown dividers cleanly');
assert.match(app, /collectFencedDivLines/, 'reader should parse fenced div blocks such as :::writing');
assert.match(app, /md-div--/, 'reader should render fenced div blocks as styled containers');
assert.match(app, /md-div-copy/, 'reader should render a copy button on fenced div cards');
assert.match(app, /block\.copied/, 'reader should toast when a fenced div is copied');
assert.match(css, /\.md-div\s*\{/, 'reader should style fenced div blocks as text boxes');
assert.match(css, /\.md-div:hover \.md-div-copy/, 'fenced div copy button should appear on hover');
assert.match(app, /fileByFullPath/, 'reader should index exported file attachments');
assert.doesNotMatch(app, /dom\.clearButton/, 'clear import should not be wired to the sidebar');
assert.doesNotMatch(app, /dom\.railClearButton/, 'clear import should not be wired to the rail');
assert.match(app, /resolveMarkdownLinkUrl/, 'reader should resolve local file links from ZIP contents');
assert.match(app, /LOCAL_FILE_REF_PREFIX/, 'reader should understand exported local file citation placeholders');
assert.match(app, /function inspectReferenceFile/, 'reader should extract file references from JSON content references');
assert.match(app, /file:\(\[\^>\]\+\?\)/, 'reader should render uploaded file placeholders from message parts');
assert.match(app, /file-attachment-card/, 'reader should render uploaded user files as attachment cards');
assert.match(app, /function fileIconSvg/, 'reader should draw a document icon for attachment cards');
assert.match(app, /renderMarkdownFileCard/, 'reader should render markdown-only file links as attachment cards');
assert.match(app, /download="\$\{escapeHtml\(link\.download\)\}"/, 'reader should download local exported files from links');
assert.match(indexHtml, /source-panel/, 'reader should render sources in a side panel');
assert.match(app, /source-button/, 'reader should expose compact source buttons');
assert.match(app, /renderSourceButtonIcon/, 'source buttons should choose icons by source type');
assert.match(app, /source-dot-icon web/, 'source buttons should render web source icons');
assert.match(app, /source-dot-icon file/, 'source buttons should render file source icons');
assert.match(app, /turn\\d\+\[a-z_\]\+\\d\+/, 'reader should clean internal citation markers including calculator refs');
assert.match(css, /transition: grid-template-columns/, 'reader should animate the sources panel');
assert.match(indexHtml, /id="searchButton"/, 'expanded sidebar should include a search action');
assert.match(indexHtml, /id="searchModal"/, 'search action should open a centered modal');
assert.match(indexHtml, /id="searchModalInput"/, 'search modal should include a search input');
assert.match(app, /renderSearchModalResults/, 'search modal should render its own results');
assert.match(indexHtml, /search-results/, 'search modal should show results');
assert.match(indexHtml, /id="turnJump"/, 'reader should include a long-conversation jump control');
assert.match(app, /buildTurnJumpItems/, 'reader should build jump targets for long conversations');
assert.match(app, /items\.length >= 5/, 'jump control should appear from five user turns');
assert.doesNotMatch(app, /items\.length > 5/, 'jump control should not hide exactly five user turns');
assert.match(css, /turn-jump-popover/, 'jump control should show a hover popover');
assert.match(app, /scrollToMessageGroup/, 'jump control should scroll to selected turns');
assert.match(app, /dom\.mainScroll\.addEventListener\("scroll", scheduleTurnJumpActiveUpdate, \{ passive: true \}\)/, 'jump control should update the active tick while scrolling');
assert.match(css, /visibility 0s linear 180ms/, 'jump control should transition smoothly instead of toggling display');
assert.match(css, /\.turn-jump-tick\s*\{[\s\S]*width: 22px/, 'jump ticks should be longer but keep a fixed length');
assert.match(css, /right: calc\(100% \+ var\(--turn-jump-popover-gap\)\)/, 'jump popover should sit beside the ticks without covering them');
assert.doesNotMatch(css, /sidebar\.search-open \.search-wrap/, 'sidebar should not expand a second search input');
assert.doesNotMatch(indexHtml, /id="searchWrap"/, 'reader should avoid duplicate sidebar search inputs');
assert.match(indexHtml, /id="sidebarScroll"/, 'expanded sidebar should put scrollable content above the fixed settings footer');
assert.match(css, /\.sidebar-panel\s*\{[\s\S]*overflow: hidden/, 'expanded sidebar panel should not create a second scrollbar');
assert.match(css, /\.sidebar-scroll\s*\{[\s\S]*overflow-y: auto/, 'sidebar content above settings should own the scrollbar');
assert.match(css, /\.main-scroll\s*\{[\s\S]*scrollbar-gutter: stable/, 'main content should reserve scrollbar width to avoid library tab layout jumps');
assert.match(css, /\.conversation-list\s*\{[\s\S]*overflow: visible/, 'conversation list should not create a nested scrollbar');
assert.match(css, /\.sidebar-footer\s*\{[\s\S]*flex: 0 0 auto/, 'settings footer should stay fixed below the sidebar scroll area');
assert.match(css, /\.sidebar-panel\.scrolled \.sidebar-actions/, 'sidebar should show a divider after scrolling');
assert.doesNotMatch(app, /focusSearchButton/, 'expanded sidebar should use the current search action id');
assert.match(app, /citation-chip/, 'reader should compact inline citations');
assert.match(app, /copyIconSvg/, 'reader should use icon-style message copy buttons');
assert.match(app, /ClipboardItem/, 'reader should copy image blobs when supported');
assert.doesNotMatch(app, /image-copy/, 'reader should reuse the message copy button for images');
assert.doesNotMatch(app, /class="image-caption"/, 'reader should not display image filenames as captions');
assert.doesNotMatch(app, /threadSource/, 'reader should not show raw source badges in the header');
assert.doesNotMatch(app, /conversation\.source === "markdown" \? "Markdown" : "JSON"/, 'conversation list should not show raw source labels');
assert.match(indexHtml, /import-summary-popup/, 'import summary should be shown as a popup');
assert.doesNotMatch(app, /showToast\(`已增量导入/, 'successful imports should use the summary popup instead of a duplicate toast');
assert.doesNotMatch(app, /showToast\(deduped\.removed \? `导入完成/, 'successful imports should not also show a bottom toast');
assert.doesNotMatch(app, /metaPanel\.classList\.add\("visible"\)/, 'import summary should not persist in the sidebar');

const sandbox = { window: {}, console, location: { hostname: 'localhost' } };
vm.runInNewContext(en, sandbox, { filename: 'en-US.js' });
vm.runInNewContext(zh, sandbox, { filename: 'zh-CN.js' });
vm.runInNewContext(zhTw, sandbox, { filename: 'zh-TW.js' });
vm.runInNewContext(i18nIndex, sandbox, { filename: 'index.js' });
const locales = sandbox.window.ChatGPTReaderLocales;
const registry = sandbox.window.ChatGPTReaderI18n.registry;
assert.deepEqual(
  Object.keys(locales['zh-CN']).sort(),
  Object.keys(locales['en-US']).sort(),
  'Simplified Chinese and English dictionaries should expose the same keys'
);
assert.deepEqual(
  Object.keys(locales['zh-TW']).sort(),
  Object.keys(locales['en-US']).sort(),
  'Traditional Chinese and English dictionaries should expose the same keys'
);
assert.equal(registry.length, 3, 'reader should register three first-party languages');
assert.ok(registry.some(locale => locale.code === 'zh-TW' && locale.nativeLabel === '繁體中文'), 'reader should expose Traditional Chinese in language settings');
assert.ok(registry.every(locale => locale.code && locale.nativeLabel && locale.dateLocale), 'registered languages should expose metadata for future expansion');

[app, en, zh, zhTw, i18nIndex].forEach((script, index) => {
  assert.doesNotThrow(
    () => new Function(script),
    `reader script ${index + 1} should parse`
  );
});

console.log('reader checks ok');
