const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('reader.html', 'utf8');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(match => match[1]);

assert.equal(scripts.length, 2, 'reader should contain embedded JSZip and app scripts');
assert.match(scripts[0], /JSZip v3\.10\.1/, 'reader should embed JSZip for offline ZIP parsing');
assert.match(html, /打开你的 ChatGPT 导出包/, 'reader should expose the ZIP drop empty state');
assert.match(html, /搜索聊天/, 'reader should include conversation search');
assert.match(html, /<div class="brand-title">ChatGPT<\/div>/, 'reader should use a ChatGPT-style sidebar title');
assert.match(html, /collapseSidebarButton/, 'reader should expose a sidebar collapse button');
assert.match(html, /sidebar-rail/, 'reader should keep a compact rail when collapsed');
assert.match(html, /expandSidebarButton/, 'reader should expose a collapsed rail expand button');
assert.match(html, /data-tooltip="打开边栏"/, 'collapsed rail buttons should show hover labels');
assert.match(html, /\.app\.sidebar-collapsed \.sidebar\s*\{[\s\S]*overflow: visible/, 'collapsed sidebar should not clip hover labels');
assert.match(html, /sidebar-collapsed/, 'reader should support collapsing the sidebar');
assert.match(html, /importChoiceModal/, 'reader should ask how to import when data already exists');
assert.match(html, /追加到当前列表/, 'reader should support append import mode at import time');
assert.match(html, /dedupeConversations/, 'reader should dedupe conversations during imports');
assert.match(html, /conversationMergeKeys/, 'reader should merge conversations with multiple dedupe keys');
assert.match(html, /conversationBranchId/, 'reader should preserve exported conversation branches during dedupe');
assert.match(html, /function countConversationTurns/, 'reader should count visible conversations by user turns');
assert.match(html, /\$\{countConversationTurns\(conversation\.messages\)\} 条/, 'conversation list should show user-turn counts');
assert.match(html, /\$\{countConversationTurns\(messages\)\} 条/, 'search fallback should show user-turn counts');
assert.doesNotMatch(html, /\$\{conversation\.messages\.length\} 条/, 'conversation list should not show raw message counts');
assert.doesNotMatch(html, /\$\{messages\.length\} 条消息/, 'search fallback should not show raw message counts');
assert.match(html, /id:\$\{conversation\.conversationId\}:\$\{conversation\.branchId\}/, 'reader should dedupe JSON conversations by branch id');
assert.doesNotMatch(html, /add\(conversation\.conversationId \? `id:\$\{conversation\.conversationId\}` : ""\)/, 'reader should not dedupe branch conversations by conversation id alone');
assert.doesNotMatch(html, /appendModeInput/, 'append import should not be a persistent sidebar toggle');
assert.doesNotMatch(html, /class="import-mode"/, 'append import should not clutter the sidebar');
assert.match(html, /window\.confirm/, 'reader should confirm before clearing imported data');
assert.match(html, /mergeConversations/, 'reader should merge conversations during append imports');
assert.match(html, /<table>/, 'reader should render markdown tables');
assert.match(html, /table-copy/, 'reader should expose copy controls for markdown tables');
assert.match(html, /table-col-label/, 'reader should reserve a stable label column for tables');
assert.match(html, /tableAlignments = line/, 'reader should parse markdown table alignment markers');
assert.match(html, /class="align-\$\{align\}"/, 'reader should apply table alignment classes');
assert.match(html, /markdown-divider/, 'reader should render markdown dividers cleanly');
assert.match(html, /fileByFullPath/, 'reader should index exported file attachments');
assert.match(html, /resolveMarkdownLinkUrl/, 'reader should resolve local file links from ZIP contents');
assert.match(html, /LOCAL_FILE_REF_PREFIX/, 'reader should understand exported local file citation placeholders');
assert.match(html, /function inspectReferenceFile/, 'reader should extract file references from JSON content references');
assert.match(html, /file:\(\[\^>\]\+\?\)/, 'reader should render uploaded file placeholders from message parts');
assert.match(html, /file-attachment-card/, 'reader should render uploaded user files as attachment cards');
assert.match(html, /function fileIconSvg/, 'reader should draw a document icon for attachment cards');
assert.match(html, /renderMarkdownFileCard/, 'reader should render markdown-only file links as attachment cards');
assert.match(html, /const link = note\?\.url \? resolveMarkdownLink\(note\.url, baseDir\)/, 'citation footnotes should resolve local ZIP files');
assert.doesNotMatch(html, /const href = note\?\.url \? safeUrl\(note\.url\) : ""/, 'citation footnotes should not drop local file paths through safeUrl');
assert.match(html, /download="\$\{escapeHtml\(link\.download\)\}"/, 'reader should download local exported files from links');
assert.match(html, /source-panel/, 'reader should render sources in a side panel');
assert.match(html, /source-button/, 'reader should expose compact source buttons');
assert.match(html, /renderSourceButtonIcon/, 'source buttons should choose icons by source type');
assert.match(html, /source-dot-icon web/, 'source buttons should render web source icons');
assert.match(html, /source-dot-icon file/, 'source buttons should render file source icons');
assert.match(html, /source-dot\$\{mixed\}/, 'source buttons should overlap icons when source types are mixed');
assert.match(html, /turn\\d\+\[a-z_\]\+\\d\+/, 'reader should clean internal citation markers including calculator refs');
assert.match(html, /transition: grid-template-columns/, 'reader should animate the sources panel');
assert.match(html, /id="searchButton"/, 'expanded sidebar should include a search action');
assert.match(html, /id="searchModal"/, 'search action should open a centered modal');
assert.match(html, /id="searchModalInput"/, 'search modal should include a search input');
assert.match(html, /renderSearchModalResults/, 'search modal should render its own results');
assert.match(html, /search-result-snippet/, 'search modal should show matched snippets');
assert.match(html, /id="turnJump"/, 'reader should include a long-conversation jump control');
assert.match(html, /buildTurnJumpItems/, 'reader should build jump targets for long conversations');
assert.match(html, /items\.length >= 5/, 'jump control should appear from five user turns');
assert.doesNotMatch(html, /items\.length > 5/, 'jump control should not hide exactly five user turns');
assert.match(html, /turn-jump-popover/, 'jump control should show a hover popover');
assert.match(html, /scrollToMessageGroup/, 'jump control should scroll to selected turns');
assert.match(html, /dom\.mainScroll\.addEventListener\("scroll", scheduleTurnJumpActiveUpdate, \{ passive: true \}\)/, 'jump control should update the active tick while scrolling');
assert.match(html, /visibility 0s linear 180ms/, 'jump control should transition smoothly instead of toggling display');
assert.match(html, /\.turn-jump-tick\s*\{[\s\S]*width: 22px/, 'jump ticks should be longer but keep a fixed length');
assert.match(html, /right: calc\(100% \+ var\(--turn-jump-popover-gap\)\)/, 'jump popover should sit beside the ticks without covering them');
assert.doesNotMatch(html, /sidebar\.search-open \.search-wrap/, 'sidebar should not expand a second search input');
assert.doesNotMatch(html, /id="searchWrap"/, 'reader should avoid duplicate sidebar search inputs');
assert.match(html, /\.sidebar-panel\s*\{[\s\S]*overflow-y: auto/, 'expanded sidebar panel should own the conversation scroll');
assert.match(html, /\.conversation-list\s*\{[\s\S]*overflow: visible/, 'conversation list should not create a nested scrollbar');
assert.match(html, /\.sidebar-panel\.scrolled \.sidebar-actions/, 'sidebar should show a divider after scrolling');
assert.doesNotMatch(html, /focusSearchButton/, 'expanded sidebar should use the current search action id');
assert.match(html, /citation-chip/, 'reader should compact inline citations');
assert.match(html, /copyIconSvg/, 'reader should use icon-style message copy buttons');
assert.match(html, /ClipboardItem/, 'reader should copy image blobs when supported');
assert.doesNotMatch(html, /image-copy/, 'reader should reuse the message copy button for images');
assert.doesNotMatch(html, /class="image-caption"/, 'reader should not display image filenames as captions');
assert.doesNotMatch(html, /threadSource/, 'reader should not show raw source badges in the header');
assert.doesNotMatch(html, /conversation\.source === "markdown" \? "Markdown" : "JSON"/, 'conversation list should not show raw source labels');
assert.doesNotMatch(html, /setStatus\(`解析 JSON/, 'import progress should not surface raw JSON labels');
assert.match(html, /import-summary-popup/, 'import summary should be shown as a popup');
assert.doesNotMatch(html, /showToast\(`已增量导入/, 'successful imports should use the summary popup instead of a duplicate toast');
assert.doesNotMatch(html, /showToast\(deduped\.removed \? `导入完成/, 'successful imports should not also show a bottom toast');
assert.doesNotMatch(html, /metaPanel\.classList\.add\("visible"\)/, 'import summary should not persist in the sidebar');

scripts.forEach((script, index) => {
  assert.doesNotThrow(
    () => new Function(script),
    `reader inline script ${index + 1} should parse`
  );
});

console.log('reader checks ok');
